title: Ben Bristow

exclude:
  - src/
  - api/
  - .cache/
  - package.json
  - package-lock.json

keep_files:
  - assets

collections:
  portfolio_items:
    output: true

defaults:
  - scope:
      type: portfolio_items
    values:
      layout: portfolio_items

plugins:
  - jekyll-feed
