title: Ben Bristow

exclude:
  - src/
  - api/
  - .cache/

collections:
  portfolio_items:
    output: true

defaults:
  - scope:
      type: portfolio_items
    values:
      layout: portfolio_items

plugins:
  - jekyll-feed