name: Build & Deploy Static Site

on:
  [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Run bundle install
      run: bundle install

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Node Dependencies
      run: npm ci

    - name: Build Assets
      run: npm run build
      
    - name: Build Jekyll site 
      run: bundle exec jekyll build

    - name: Deploy to Azure Blob Storage
      uses: bacongobbler/azure-blob-storage-upload@v1.1.0
      with:
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container_name: '$web'
          source_dir: '_site'
          sync: true
