name: Build & Deploy Static Site

on:
  [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Ruby Gem Cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Run bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Node Dependencies
      uses: bahmutov/npm-install@v1

    - name: Build Assets
      run: npm run build
      
    - name: Build Jekyll site 
      run: bundle exec jekyll build

    - name: Deploy to Azure Blob Storage
      uses: bacongobbler/azure-blob-storage-upload@v1.1.0
      with:
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container_name: '$web'
          source_dir: '_site'
          sync: true
